name: Release Package

on:
  release:
    types: [published]

env:
  NUGET_API_KEY:

jobs:
  release-serviurtium-core:
    if: ${{ contains(github.ref, 'refs/tags/servirtium.core/v') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
#     - name: Determine Version
#       uses: paulhatch/semantic-version@v4.0.2
#       id: semantic_version
#       with:
#         format: "${major}.${minor}.${patch}-dev.{increment}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Extract version from ref
        uses: actions/github-script@v4
        id: extract-version
        with:
          script: return /refs\/tags\/servirtium\.core\/v(.+)/.exec(context.ref)[1]
      - name: Nuget Pack
        env:
          VERSION: ${{ steps.extract-version.outputs.result }}
        run: dotnet pack ./Servirtium.Core/Servirtium.Core.csproj --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Nuget Push
        run: dotnet push Servirtium.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}

